# Generated by Django 4.1.7 on 2023-03-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_doctor_profile_alter_patient_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brief', models.TextField(max_length=50)),
                ('Dep_image', models.ImageField(default='', upload_to='main_app/static/images/department')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_Number',
            field=models.CharField(max_length=5000),
        ),
    ]
