# Generated by Django 4.1.7 on 2023-03-19 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_department_alter_profile_mobile_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='Dep_image',
            new_name='image',
        ),
    ]
