# Generated by Django 4.1.7 on 2023-03-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_department_brief'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_Number',
            field=models.CharField(default='0000', max_length=5000),
        ),
    ]
