# Generated by Django 4.1.7 on 2023-03-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_appointment_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='blood',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='cpr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dof',
            field=models.DateField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='height',
            field=models.FloatField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sensitivity',
            field=models.TextField(max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='weight',
            field=models.FloatField(max_length=5, null=True),
        ),
    ]
